on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup_repo:
    name: Setup the repository
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: cp -r firebase/* .
      - run: npm install
      - run: npm install -g firebase-tools # Install Firebase CLI
      - run: echo "FIREBASE_PROJECT_ID ${{ env.FIREBASE_PROJECT_ID }}"
      - run: node updateFirebaseConfig.js ${{ env.FIREBASE_PROJECT_ID }}
      - run: cat lib/backend/firebase/firebase_config.dart
      - name: Upload Required Files
        uses: actions/upload-artifact@v2
        with:
          name: setup-files
          path: |
            lib/backend/firebase/firebase_config.dart
            firebase.json
            .firebaserc
            storage.rules
            firestore.rules
            firestore.indexes.json
            functions/**/*

  build_web:
    needs: setup_repo
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Setup Files
        uses: actions/download-artifact@v2
        with:
          name: setup-files
          path: .
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Replace with your project's version of Flutter.
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - name: Upload Web Build
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

  deploy:
    needs: build_web
    runs-on: ubuntu-latest  
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download Setup Files
        uses: actions/download-artifact@v2
        with:
          name: setup-files
          path: .
      - name: Download Web Build
        uses: actions/download-artifact@v2
        with:
          name: web-build
          path: build/web
      - run: npm install
      - run: npm install --save firebase-functions@latest
      - run: npm install -g firebase-tools # Install Firebase CLI
      - name: Deploy to Firebase
        id: deploy
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ secrets.FIREBASE_PROJECT_ID }} > output.txt
          cat output.txt
          echo "::set-output name=hosting_url::$(grep -o 'https://.*\.web\.app' output.txt)"
      - name: Check Hosting URL
        run: echo "The Hosting URL is: ${{ steps.deploy.outputs.hosting_url }}"
