on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup_repo:
    name: Setup the repository
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v2
      - run: cp -r firebase/* .
      - run: npm install
      - run: echo FIREBASE_PROJECT_ID ${{ env.FIREBASE_PROJECT_ID }}
      - run: node updateFirebaseConfig.js ${{ env.FIREBASE_PROJECT_ID }}
      - run: cat lib/backend/firebase/firebase_config.dart

  build_web:
    needs: setup_repo
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Replace with your project's version of Flutter.
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

  deploy:
    needs: build_web
    runs-on: ubuntu-latest  
    env:
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: web-build
          path: build/web
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
